import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Login.module.css'
import { useRouter } from 'next/router'
import { supabase } from '../../supabase';
import NewLogo from '../../public/logo.svg';

export default function Login() {

  const router = useRouter();

  async function handleLogin(e){
    e.preventDefault();
    const email = document.getElementById('email').value;
    const password = document.getElementById('password').value;
    try{
      const{data,error}=await supabase.auth.signInWithPassword({
        email,
        password,
      });
      if(error){
        console.log("Erro ao fazer login: ", error.message);
      }else{
        console.log(data);
        router.push('/dashboard');
      }
    } catch (error){
      console.error("Erro inesperado: ", error);
    }
  }
  return (
    <>
      <Head>
        <title>Grade+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <div className={styles.logoTexto}>
          <Image priority src={NewLogo} width={500} height={200} alt='logo'/>
          {/* GRADE
          <div className={styles.logoMais}>
            +
          </div> */}
        </div>

        <Image priority src='/login_illustration.png' width={500} height={500} alt='illustration' style={{
          position:'absolute',
          top: '20rem',
          left: '10rem',
        }}/>

        <div className={styles.textbox}>
          <h1>Olá,</h1>
          <p>É bom te ver novamente!</p>
        </div>

        <form className={styles.formLogin} onSubmit={handleLogin}>
          <div className={styles.inputWrapper}>
            <input className={styles.inputStyle} type='text' id='email' name='email' required/>
            <label>Email</label>
          </div>
          <div className={styles.inputWrapper}>
            <input type='password' id='password' name='password' required/>
            <label>Senha</label>
          </div>
          <button className={styles.btnSubmitLogin} type='submit'>Entrar</button>
        </form>

        <div className={styles.goSignUp}>
          <div>
            <span>Ainda não é usuário? </span>
            <button style={{color:'#9747FF'}} onClick={() => router.push('/signup')}> Cadastre-se</button>
          </div>
          <div>
            <button>Esqueci a senha</button>
          </div>
        </div>

        <button className={styles.btnGoogle}>
          <Image src='/google_icon.png' priority width={20} height={20} alt='google'/>
          <span>Entre com o Google</span>
        </button>

      </main>
    </>
  )
}