import Head from 'next/head'
import Image from 'next/image'
// import { League_Gothic } from 'next/font/google'
import styles from '@/styles/SignUp.module.css'
import { useRouter } from 'next/router'


// const league_gothic = League_Gothic({ subsets: ['latin'] })

export default function SignUp() {
    const router = useRouter();

  return (
    <>
      <Head>
        <title>Grade+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>

        <section className={styles.leftContainer}>

            <div className={styles.logoTexto}>
            <h1>GRADE+</h1>
            </div>

            <div className={styles.containerLeftImage}>
            <Image priority src='/figure_student.png' fill alt='illustration' style={{
                objectFit:'contain'
            }}/>
            </div>

        </section>

        <section className={styles.rightContainer}>
            

            <form className={styles.formLogin}>

            <div className={styles.textbox}>
            <h1>OK,</h1>
            <p>Vamos criar sua conta!</p>
            </div>

            <div className={styles.inputWrapper}>
                <input className={`${styles.inputStyle} ${styles.wideInput}`} type='text' id='name' name='name' required/>
                <label>Nome</label>
            </div>

            <div className={styles.inputWrapper}>
                <input className={`${styles.inputStyle} ${styles.wideInput}`} type='email' id='email' name='email' required/>
                <label>Email</label>
            </div>

            <div className={styles.setPassContainer}>
                <div className={styles.inputWrapper}>
                    <input className={styles.shortInput} type='password' id='setpassword' name='setpassword' required/>
                    <label>Senha</label>   
                </div>

                <div className={styles.inputWrapper}>
                    <input className={styles.shortInput} type='password' id='checkpassword' name='checkpassword' required/>
                    <label>Confirme a senha</label>
                </div>
            </div>
            
            <button className={styles.btnSubmitLogin} type='submit'>Cadastrar</button>
            </form>
            <span>Já possui uma conta? Faça <button style={{color:'#9747FF'}} onClick={() => router.push('/')}>login!</button></span>
            <span style={{fontWeight:'lighter'}}>Ao se registrar, você concorda com nossos Termos de Uso e Políticas de Privacidade</span>
        </section>
      </main>
    </>
  )
}